      - name: Build APK
        working-directory: ${{ env.PROJECT_DIR }}
        shell: bash
        run: |
          echo "===== PROJECT ====="
          pwd
          find . -maxdepth 3 -type f | sort

          echo "===== JAVA ====="
          java -version

          echo "===== GRADLE ====="
          gradle --version

          echo "===== SETTINGS ====="
          cat settings.gradle.kts

          echo "===== ROOT BUILD ====="
          cat build.gradle.kts

          echo "===== APP BUILD ====="
          cat app/build.gradle.kts

          echo "===== BUILD ====="
          gradle :app:assembleDebug --stacktrace --info --no-daemon
